@startuml
title Bank Standart Context Diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person_Ext(user, "Пользователь", "Клиент")
System_Ext(sms_gate, "SMS-шлюз", "Процессинг сообщений")
Person(manager, "Сотрудник отдела депозитов")
Person(call, "Сотрудник кол-центра")
System(internet_bank, "Интернет-банк", "Система интернет-банкинга")
System(site, "Сайт", "Сайт банка Стандарт")
System(deposit_system, "Система депозитов", "Система управления депозитами")
System(call_system, "Система кол-центра", "Система управления заявками кол-центра")
System(abs, "АБС", "Автоматизированная банковская система")

Rel(user, internet_bank, "Подает заявку на открытие депозита")
Rel(user, site, "Подает заявку на открытие депозита")
Rel(user, call, "Подает заявку через кол-центр")
Rel(manager, abs, "Контролирует ставки на депозиты")
Rel(internet_bank, abs, "Заявка падает в систему АБС")
Rel(site, abs, "Заявка падает в систему АБС")
Rel(call, call_system, "Отправляет заявку")
Rel(call_system, abs, "Создает заявку в системе АБС")
BiRel_R(abs, deposit_system, "Обработка заявки")
Rel(abs, sms_gate, "Отправляет сообщение о статусе ответа по заявке")
@enduml
